### ISSUE TITLE
Bootstrap Version

### ISSUE THREAD

**Issue by NowNewStart** [AndreasElia/laravel-forum#37]
imo we should just use Bootstrap 4, I feel like we're better off with it. Opinions?

**Comment by AndreasElia** [comment]
@NowNewStart people using the package are likely to be running it in a production environment where a lot of people are still holding off on BS4 and sticking with BS3. I'm open to this changing, but is there really a reason to?

**Comment by Dylan-DPC** [comment]
We can't use bootstrap 4.. since people looking to use this package will be using BS3. Eventually "down the road" we need to make it flexible in a way that users can use it with any UI libary or even their own custom stuff

**Comment by Riari** [comment]
Changing from Boostrap should only ever be a case of overriding views anyway. It's fine to just throw the Bootstrap CSS and JS into the package's main view via a CDN because this view is almost guaranteed to be overridden to make it sit inside the app's main view, where the dev will no doubt have their own choice of frontend stuff loaded.

**Comment by AndreasElia** [comment]
As @Riari said the user is likely to be overriding the views (or at least the template). Bootstrap 3 via CDN will be more than enough and is only 2 lines of code to change if the user doesn't want it.
